version : '3'
services:
  webservice:
    build:
      context : "/home/ec2-user"
      dockerfile : "Dockerfile.app"
  appservice:
    build:
      context : "."
      dockerfile : "Dockerfile.tomcat"
   


