version : '3'
services:
  webservice:
    build:
      context : "/home/ec2-user"
      dockerfile : "Dockerfile.app"
    ports:
      - "80:80"
  appservice:
    build:
      context : "."
      dockerfile : "Dockerfile.tomcat"
    ports:
      - "90:8080"
   


